pkgs: let
  patchedLib = import ../patched-nixpkgs-lib pkgs;
  autogenerationWarning = ''
    # This file was automatically generated by the Modulix flake generator
    # and will be overwritten without warning on subsequent runs of the generator.'';
  helpMessage = ''
    Generate a flake.nix file from the inputs defined in Modulix modules. Automatically adds nixpkgs, home-manager, and modulix to the flake inputs if they are missing.

    Usage: mxg [OPTIONS]

    Options:
      -f, --force        Ignore the overwrite warning that appears if the autogeneration warning is not present in the flake.nix file
      -p, --path <PATH>  The configuration directory (defaults to /etc/nixos)
      -h, --help         Print this help'';
in
  pkgs.writeShellApplication {
    name = "mxg";
    runtimeInputs = with pkgs; [coreutils getopt nix];
    text = ''
      args=$(getopt -n 'mxg' -o fp:h -l force,path:,help -- "$@")
      eval set -- "$args"

      force=false
      path=/etc/nixos
      while true; do
        case "$1" in
          -f|--force ) force=true; shift;;
          -p|--path ) path="$2"; shift 2;;
          -h|--help ) echo '${helpMessage}'; exit;;
          -- ) break;;
        esac
      done

      if [[ ! -f $path/config.nix ]]; then
        echo "'$path/config.nix' is missing"
        exit 1
      fi

      if [[ $force == false && -f $path/flake.nix && $(cat "$path/flake.nix") != '${autogenerationWarning}'* ]]; then
        while true; do
          read -rn 1 -p "'$path' contains a flake.nix file without the autogeneration warning left by this generator."$'\nDo you want to overwrite this file? ' result
          case "$result" in
            [Yy] ) echo; break;;
            [Nn] ) exit 1;;
            * ) echo;;
          esac
        done
      fi

      tmp=$(mktemp -t flake.nix.XXXXX)
      trap 'rm "$tmp"' ERR

      nix-instantiate --eval --raw --argstr libPath '${patchedLib}' --argstr configPath "$path/config.nix" --argstr autogenerationWarning '${autogenerationWarning}' '${./generate-flake.nix}' > "$tmp"

      mv "$tmp" "$path/flake.nix"
      echo "Successfully generated '$path/flake.nix'!"
    '';
  }
